default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'password' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: <%= ENV['PG_PROD_USERNAME'] %>
  password: <%= ENV['PG_PROD_PASSWORD'] %>
  host: <%= ENV['PG_PROD_HOST'] %>
